backend:
  name: github
  repo: human-first-tech/random-musings-blog
  branch: main
  base_url: https://www.d-island-girl.com
  auth_endpoint: api/auth

media_folder: public/images
public_folder: /images

collections:
  - name: posts
    label: Posts
    label_singular: Post
    folder: content/posts
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Publish Date, name: date, widget: datetime, format: YYYY-MM-DD, date_format: YYYY-MM-DD, time_format: false }
      - { label: Slug, name: slug, widget: string }
      - { label: Tags, name: tags, widget: list }
      - { label: Excerpt, name: excerpt, widget: text }
      - { label: Body, name: body, widget: markdown }
